<?php
/* Reference front controller for Hostinger PHP plans. Install stripe/stripe-php, paypal/rest-api-sdk-php, twilio/sdk and dompdf/dompdf with Composer. */
require __DIR__.'/vendor/autoload.php'; header('Content-Type: application/json');
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);$raw=file_get_contents('php://input');$data=json_decode($raw,true)??[];
$pdo=new PDO(getenv('DATABASE_URL'),null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
function json_out($body,$code=200){http_response_code($code);echo json_encode($body);exit;}
if($path==='/api/order'){$id=bin2hex(random_bytes(16));$q=$pdo->prepare("INSERT INTO orders(public_id,email,service,duration_months,amount_cents,status) VALUES(?,?,?,?,?,'pending')");$q->execute([$id,filter_var($data['email'],FILTER_VALIDATE_EMAIL),$data['service'],(int)$data['duration'],(int)$data['amount']]);json_out(['orderId'=>$id],201);}
if($path==='/api/create-payment-session'){\Stripe\Stripe::setApiKey(getenv('STRIPE_SECRET'));$s=\Stripe\Checkout\Session::create(['mode'=>'payment','line_items'=>[['quantity'=>1,'price_data'=>['currency'=>'eur','unit_amount'=>(int)$data['amount'],'product_data'=>['name'=>$data['service']]]]],'metadata'=>['orderId'=>$data['orderId']],'success_url'=>getenv('PUBLIC_URL').'/tariffe.html?paid=1','cancel_url'=>getenv('PUBLIC_URL').'/tariffe.html']);json_out(['url'=>$s->url]);}
if($path==='/api/webhook/stripe'){try{$event=\Stripe\Webhook::constructEvent($raw,$_SERVER['HTTP_STRIPE_SIGNATURE']??'',getenv('STRIPE_WEBHOOK_SECRET'));if($event->type==='checkout.session.completed'){$s=$event->data->object;$q=$pdo->prepare("UPDATE orders SET status='paid',provider='stripe',provider_reference=? WHERE public_id=?");$q->execute([$s->id,$s->metadata->orderId]);}json_out(['received'=>true]);}catch(Throwable $e){json_out(['error'=>'Invalid signature'],400);}}
if($path==='/api/send-otp'){$code=(string)random_int(100000,999999);$hash=hash_hmac('sha256',$data['orderId'].':'.$code,getenv('OTP_SECRET'));$q=$pdo->prepare("INSERT INTO otp_verifications(order_public_id,phone,code_hash,expires_at) VALUES(?,?,?,NOW()+INTERVAL '10 minutes')");$q->execute([$data['orderId'],$data['phone'],$hash]);$twilio=new \Twilio\Rest\Client(getenv('TWILIO_ACCOUNT_SID'),getenv('TWILIO_AUTH_TOKEN'));$twilio->messages->create($data['phone'],['from'=>getenv('TWILIO_FROM'),'body'=>'Roma Office Sharing: '.$code]);json_out(['ok'=>true]);}
if($path==='/api/verify-otp'){$q=$pdo->prepare("SELECT * FROM otp_verifications WHERE order_public_id=? AND expires_at>NOW() AND attempts<5 ORDER BY id DESC LIMIT 1");$q->execute([$data['orderId']]);$r=$q->fetch(PDO::FETCH_ASSOC);$actual=hash_hmac('sha256',$data['orderId'].':'.$data['code'],getenv('OTP_SECRET'));if(!$r||!hash_equals($r['code_hash'],$actual))json_out(['error'=>'Invalid'],400);json_out(['ok'=>true]);}
if($path==='/api/save-signature'){$html='<h1>Domiciliation request</h1><p>Order '.htmlspecialchars($data['orderId']).'</p><img width="300" src="'.htmlspecialchars($data['signature']).'">';$pdf=new \Dompdf\Dompdf();$pdf->loadHtml($html);$pdf->render();header('Content-Type: application/pdf');echo $pdf->output();exit;}
if($path==='/api/webhook/paypal'){/* Verify with PayPal verify-webhook-signature endpoint before marking paid. */json_out(['received'=>true]);}
if($path==='/api/webhook/esign'){/* Verify provider HMAC/certificate, fetch the signed file server-side, store a private key. */json_out(['received'=>true]);}
json_out(['error'=>'Not found'],404);
