import Link from "next/link";
import { ArrowRight, Building2, Check, FileCheck2, Mail, MapPin, ShieldCheck } from "lucide-react";
import { reverseRouteMap, type Lang } from "@/lib/site";

type Detail = { title: string; intro: string; audience: string; includes: string[]; note: string };
const detailCopy: Record<string, Record<Lang, Detail>> = {
  "domiciliazione-sede-legale.html": {
    it: { title: "Una sede per la tua società. Un punto di riferimento per la tua posta.", intro: "Scegli Via Venti Settembre, 118 come sede legale della tua attività: un indirizzo nel centro di Roma, con una reception che riceve e custodisce la corrispondenza secondo le condizioni del contratto. Non è necessario affittare un ufficio operativo per usufruire del servizio.", audience: "Per società di nuova costituzione, aziende che trasferiscono la sede e ditte individuali, previa verifica dei requisiti della singola attività. Per una nuova società l’indirizzo può essere indicato nell’atto costitutivo; per una società esistente occorre comunicare la variazione agli enti competenti con il supporto del proprio consulente.", includes: ["Utilizzo dell’indirizzo come sede legale, dopo la conferma di attivazione", "Indicazione dell’indirizzo su documenti aziendali, sito web e corrispondenza, nei limiti del contratto", "Ricezione e custodia della posta indirizzata all’attività, inclusi plichi e raccomandate nei limiti delle deleghe conferite", "Ritiro da parte del legale rappresentante o di un delegato; inoltro da concordare separatamente"], note: "La domiciliazione non sostituisce una sede operativa né le autorizzazioni richieste per l’attività. Le pratiche presso Registro Imprese e Agenzia delle Entrate restano a cura del cliente o del suo consulente." },
    en: { title: "An address for your company. A reliable home for your mail.", intro: "Choose Via Venti Settembre, 118 as your registered office address: a central Rome location with a reception team that receives and safely holds correspondence under your agreement. You do not need to rent a physical working office to use this service.", audience: "For newly incorporated companies, businesses relocating their registered office and sole proprietors, subject to the requirements of each business. New companies can include the address in their incorporation documents; existing companies must notify the relevant Italian authorities of the change with their adviser’s support.", includes: ["Use of the address as your registered office once activation is confirmed", "Use on company documents, your website and correspondence within the agreement’s scope", "Receipt and safekeeping of business mail, including parcels and registered letters subject to the authorisations provided", "Collection by the legal representative or an authorised person; forwarding by separate arrangement"], note: "A registered office address does not replace an operating location or any licences required for your business. Filings with the Italian Business Register and Revenue Agency remain the responsibility of the client or their adviser." },
  },
  "domiciliazione-postale.html": {
    it: { title: "La tua posta aziendale, in mani affidabili.", intro: "Un recapito professionale a Roma per ricevere comunicazioni commerciali, lettere e plichi senza utilizzare l’indirizzo di casa. La corrispondenza viene custodita e resa disponibile al ritiro secondo le modalità concordate.", audience: "Per professionisti, lavoratori da remoto e imprese che desiderano un indirizzo di corrispondenza separato dall’abitazione, senza trasferire la sede legale.", includes: ["Uso dell’indirizzo come recapito postale e commerciale", "Ricezione della corrispondenza negli orari di reception", "Custodia della posta e ritiro personale o tramite delegato", "Possibilità di concordare l’inoltro, con modalità e costi da confermare"], note: "Il servizio postale non autorizza a registrare la sede legale presso il centro. Per questa esigenza scegli la domiciliazione sede legale." },
    en: { title: "Your business mail, in reliable hands.", intro: "A professional mailing address in Rome for business correspondence, letters and parcels—without using your home address. Mail is safely held and made available for collection under the agreed arrangements.", audience: "For professionals, remote workers and businesses who want a mailing address separate from home, without changing their company’s registered office.", includes: ["Use of the address for business correspondence and commercial communications", "Receipt of mail during reception opening hours", "Safekeeping and collection in person or by an authorised representative", "Optional forwarding by agreement, with arrangements and charges confirmed in advance"], note: "The mailing-only service does not authorise company registration at the address. If you need an official company address, choose the registered office service." },
  },
  "domiciliazione-professionale.html": {
    it: { title: "Un indirizzo professionale, distinto dalla tua abitazione.", intro: "Presenta la tua attività con un recapito a Roma e affida al centro la ricezione della corrispondenza. Un servizio flessibile per chi lavora in mobilità o desidera separare vita privata e comunicazioni professionali.", audience: "Per liberi professionisti e consulenti. L’eventuale uso come domicilio professionale va verificato in base alle regole del proprio Ordine, albo o attività.", includes: ["Indirizzo professionale per comunicazioni e recapito", "Ricezione e custodia della corrispondenza", "Ritiro con identificazione o delega", "Uffici e sale prenotabili separatamente, in base alla disponibilità"], note: "Il servizio non include l’uso continuativo di una postazione e non sostituisce requisiti professionali, autorizzazioni o comunicazioni previste dalla legge." },
    en: { title: "A professional address, separate from your home.", intro: "Give your practice a Rome business address and let the centre receive your correspondence. A flexible service for mobile professionals and anyone wishing to keep personal and professional communications separate.", audience: "For independent professionals and consultants. Use as an official professional address must be checked against the rules of the relevant professional body or activity.", includes: ["A professional address for correspondence and contact details", "Receipt and safekeeping of mail", "Collection with identification or written authorisation", "Offices and meeting rooms bookable separately, subject to availability"], note: "The service does not include a permanent workstation or replace any professional requirements, licences or statutory notifications." },
  },
  "domiciliazione-ditta-individuale.html": {
    it: { title: "Dai un indirizzo professionale alla tua impresa.", intro: "Organizza la presenza della tua ditta individuale a Roma con un indirizzo dedicato e un punto di raccolta per la posta. Scegli durata e decorrenza del contratto in base ai tuoi programmi.", audience: "Per titolari di ditte individuali, già avviate o in fase di apertura. Verifichiamo insieme la soluzione prima dell’utilizzo dell’indirizzo nelle pratiche dell’impresa.", includes: ["Indirizzo per la ditta individuale secondo l’uso previsto dal contratto", "Ricezione delle comunicazioni aziendali", "Custodia e consegna al titolare o al delegato", "Durate da 3 a 48 mesi per il servizio sede legale / unità locale"], note: "L’idoneità dell’indirizzo dipende dall’attività svolta. Verifica con il tuo consulente gli adempimenti fiscali e amministrativi necessari." },
    en: { title: "Give your business a professional address.", intro: "Establish your sole proprietorship’s presence in Rome with a dedicated address and a collection point for business mail. Choose a contract duration and start date that suit your plans.", audience: "For owners of existing or newly established sole proprietorships. We review the appropriate service with you before you use the address in business filings.", includes: ["An address for your sole proprietorship for the purposes agreed in the contract", "Receipt of business correspondence", "Safekeeping and handover to the owner or an authorised person", "Terms of 3 to 48 months for the registered office / local unit address service"], note: "Suitability depends on your business activity. Check the necessary tax and administrative requirements with your adviser." },
  },
  "domiciliazione-unita-locale.html": {
    it: { title: "Un punto di presenza per la tua attività a Roma.", intro: "Se la tua azienda ha già una sede principale, valuta un indirizzo a Roma per l’unità locale. Il servizio unisce un recapito professionale e la gestione della corrispondenza, con condizioni definite prima dell’attivazione.", audience: "Per imprese che intendono aprire o trasferire un’unità locale, previa verifica dell’attività dichiarata e dei requisiti previsti dagli enti competenti.", includes: ["Uso dell’indirizzo per l’unità locale nei limiti autorizzati dal contratto", "Ricezione della corrispondenza destinata all’unità locale", "Custodia e ritiro tramite il referente o il delegato", "Uffici e sale disponibili su prenotazione con accordo separato"], note: "L’indirizzo da solo non costituisce una sede operativa attrezzata e non garantisce l’iscrizione per qualunque attività. Le caratteristiche dell’unità locale devono essere verificate con il consulente." },
    en: { title: "A Rome presence for your business.", intro: "If your company already has a main office, consider a Rome address for a local unit. The service combines a professional contact address and mail handling, with terms confirmed before activation.", audience: "For businesses opening or relocating an Italian local unit, subject to checks on the declared activity and the requirements of the relevant authorities.", includes: ["Use of the local unit address within the scope authorised by your agreement", "Receipt of correspondence addressed to the local unit", "Safekeeping and collection by your contact person or representative", "Offices and meeting rooms available by reservation under a separate agreement"], note: "An address alone is not an equipped operating office and does not guarantee registration for every type of activity. Review the local unit’s requirements with your adviser." },
  },
};

export function hasAddressDetail(key: string) { return Boolean(detailCopy[reverseRouteMap[key] || key]); }
export function AddressServiceDetails({ pageKey, lang }: { pageKey: string; lang: Lang }) {
  const it = lang === "it"; const key = reverseRouteMap[pageKey] || pageKey; const copy = detailCopy[key][lang];
  const postal = key === "domiciliazione-postale.html";
  const contact = it ? "/contatti.html" : "/en/contact.html";
  const faq = it ? [
    ["Posso utilizzare subito l’indirizzo?", "Attendi la conferma scritta di attivazione e verifica documentale prima di indicare l’indirizzo negli atti o nelle comunicazioni ufficiali."],
    ["Come ritiro la corrispondenza?", "Il ritiro avviene durante gli orari di reception, da parte del titolare, legale rappresentante o persona delegata. Per inoltri, dimensioni dei plichi e servizi aggiuntivi concorda prima modalità e costi con il centro."],
    ["Quali documenti devo preparare?", "Generalmente servono documento di identità e codice fiscale del rappresentante, visura camerale o dati di costituzione e le deleghe previste. Per una nuova impresa comunicherai i dati definitivi dopo la costituzione. La reception confermerà l’elenco per la tua pratica."],
    ["È incluso un ufficio fisico?", "No. L’indirizzo e la gestione postale sono distinti dall’affitto di un ufficio. Se ti serve uno spazio per lavorare o incontrare i clienti, puoi richiedere un ufficio giornaliero o una sala."],
  ] : [
    ["Can I use the address straight away?", "Wait for written activation and document-check confirmation before using the address in incorporation documents or official communications."],
    ["How do I collect my mail?", "The owner, legal representative or an authorised person can collect mail during reception hours. Please agree forwarding arrangements, parcel limits and any additional charges with the centre in advance."],
    ["Which documents should I prepare?", "Typically, the representative’s ID and tax code, a company register extract or incorporation details, and the relevant authorisations. For a new business, final details follow incorporation. Reception will confirm the checklist for your application."],
    ["Is a physical office included?", "No. Address and mail-handling services are separate from office rental. If you need space to work or meet clients, ask about a day office or meeting room."],
  ];
  return <>
    <section className="section shell address-intro"><div className="address-main"><span className="eyebrow">{it ? "LA TUA ATTIVITÀ, IL NOSTRO SUPPORTO" : "YOUR BUSINESS, OUR SUPPORT"}</span><h2>{copy.title}</h2><p className="lead">{copy.intro}</p><h3>{it ? "A chi è rivolto" : "Who it is for"}</h3><p>{copy.audience}</p><div className="address-includes"><h3>{it ? "Cosa comprende il servizio" : "What the service includes"}</h3><ul className="check-list">{copy.includes.map(item => <li key={item}><Check />{item}</li>)}</ul></div></div><aside className="address-card"><MapPin /><span className="eyebrow">{it ? "IL TUO INDIRIZZO A ROMA" : "YOUR ROME ADDRESS"}</span><h3>Via Venti Settembre, 118</h3><p>Palazzo Gentiloni · int. 1<br />00187 Roma</p><div className="address-card-note"><ShieldCheck />{it ? "Un recapito professionale. Un team a cui affidarti." : "A professional address. A team you can rely on."}</div><Link href={postal ? (it ? "/attiva.html?service=postal" : "/en/activate.html?service=postal") : (it ? "/attiva.html?service=legal_unit" : "/en/activate.html?service=legal_unit")} className="button primary">{it ? "Attiva subito" : "Activate now"}<ArrowRight /></Link><Link className="arrow-link" href={it ? "/tariffe.html" : "/en/pricing.html"}>{it ? "Consulta tariffe e offerte" : "View pricing & offers"}<ArrowRight /></Link></aside></section>
    <section className="address-process"><div className="shell"><div className="section-heading"><div><span className="eyebrow">{it ? "SEMPLICE, DALL’INIZIO" : "STRAIGHTFORWARD FROM THE START"}</span><h2>{it ? "Dalla richiesta alla tua nuova sede." : "From your enquiry to your new address."}</h2></div><p>{it ? "Ti accompagniamo nella scelta del servizio e nella raccolta dei dati, senza confondere l’attivazione del contratto con le pratiche societarie." : "We help you choose the service and provide the necessary information, keeping contract activation distinct from statutory company filings."}</p></div><div className="address-steps">{[{ Icon: FileCheck2, title: it ? "Prepara la richiesta" : "Prepare your application", text: it ? "Inserisci dati aziendali e del rappresentante, durata e decorrenza. Verifica il cellulare con il codice SMS." : "Enter company and representative details, duration and start date. Verify your mobile with an SMS code." }, { Icon: Building2, title: it ? "Conferma il servizio" : "Confirm your service", text: it ? "Completa pagamento e documentazione. L’utilizzo dell’indirizzo decorre dalla conferma del centro e dalla data concordata." : "Complete payment and provide the required documents. Address use begins after the centre’s confirmation and on the agreed date." }, { Icon: Mail, title: it ? "Gestisci la tua posta" : "Manage your mail", text: it ? "La reception riceve la corrispondenza. Organizza il ritiro o l’eventuale inoltro secondo gli accordi." : "Reception receives your correspondence. Arrange collection or optional forwarding under your agreement." }].map(({ Icon, title, text }, i) => <article key={title}><span className="step-number">0{i + 1}</span><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section shell address-faq"><div><span className="eyebrow">FAQ</span><h2>{it ? "Le risposte, prima di scegliere." : "Answers before you decide."}</h2><p>{copy.note}</p><Link className="arrow-link" href={postal ? (it ? "/domiciliazione-sede-legale.html" : "/en/legal-headquarters-domiliation.html") : (it ? "/domiciliazione-postale.html" : "/en/postal-domiliation.html")}>{postal ? (it ? "Scopri la sede legale" : "Explore registered office addresses") : (it ? "Ti serve solo un recapito postale?" : "Only need a mailing address?")}<ArrowRight /></Link></div><div>{faq.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
  </>;
}
