import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Check, Clock3, FileCheck2, Mail, MapPin, MonitorSmartphone, Phone, Quote, TrainFront } from "lucide-react";
import { ContactForm } from "./Interactive";
import { ActivationFlow } from "./ActivationFlow";
import { Gallery, GalleryPreview } from "./Gallery";
import { CustomerArea } from "./CustomerArea";
import { AddressServiceDetails, hasAddressDetail } from "./AddressServices";
import { BrandWords } from "./BrandWords";
import { type ServiceCode } from "@/lib/pricing";
import { getCatalog } from "@/lib/catalog";
import { PricingOffer } from "./PricingOffers";
import { alternateFor, contact, hrefFor, pages, privacySections, services, ui, type Lang } from "@/lib/site";

const icons = { desk: Building2, building: BadgeCheck, mail: Mail, monitor: MonitorSmartphone };
export function PageView({ pageKey, lang, initialService = "legal_unit" }: { pageKey: string; lang: Lang; initialService?: ServiceCode }) {
  const page = pages[pageKey]; const t = ui[lang]; const it = lang === "it"; const home = lang === "it" ? "/" : "/en/index.html";
  return <main id="main">
    {page.kind === "home" ? <>
      <section className="hero home-hero">
        <Image src="/images/office-hero.jpg" alt={it ? "Ufficio arredato moderno e luminoso" : "Bright modern furnished office"} fill priority sizes="100vw" />
        <div className="hero-shade" /><div className="hero-content shell"><span className="eyebrow light"><BrandWords /></span><h1>{page.title}</h1><p>{page.description}</p><div className="hero-actions"><Link href={it ? "/attiva.html" : "/en/activate.html"} className="button accent">{t.activateNow}<ArrowRight /></Link><Link href={it ? "/tariffe.html" : "/en/pricing.html"} className="hero-secondary">{it ? "VEDI TARIFFE E OFFERTE" : "SEE PRICING & OFFERS"}</Link><a href={`tel:${contact.phoneHref}`} className="call-link"><Phone />{t.call}</a></div></div>
        <div className="hero-facts shell"><div><b>2014</b><span>{it ? "al fianco delle imprese" : "supporting businesses"}</span></div><div><b>Roma</b><span>{it ? "centro, a due passi da Termini" : "centre, steps from Termini"}</span></div><div><b>8:30–18:00</b><span>{it ? "reception dedicata" : "dedicated reception"}</span></div></div>
      </section>
      <section className="section shell"><div className="section-heading"><div><span className="eyebrow">{it ? "SOLUZIONI" : "SOLUTIONS"}</span><h2>{it ? "Tutto ciò che serve al tuo business" : "Everything your business needs"}</h2></div><p>{it ? "Spazi, indirizzo e servizi professionali in un unico luogo, con la flessibilità di scegliere solo ciò che serve." : "Workspace, business address and professional services in one place—with the flexibility to choose only what you need."}</p></div><ServiceGrid lang={lang} /></section>
      <section className="split-section"><div className="split-image"><Image src="/images/office-hero.jpg" alt="" fill sizes="50vw" /></div><div className="split-copy"><span className="eyebrow">PALAZZO GENTILONI</span><h2>{it ? "Il prestigio della storia, l’efficienza del presente" : "Historic prestige, modern efficiency"}</h2><p>{it ? "Al primo piano di Palazzo Gentiloni, ambienti curati e tecnologie all’avanguardia accolgono il tuo lavoro e i tuoi clienti." : "On the first floor of Palazzo Gentiloni, refined spaces and up-to-date technology welcome you, your work and your clients."}</p><ul className="check-list"><li><Check />{it ? "Posizione centrale e rappresentativa" : "Central, prestigious location"}</li><li><Check />{it ? "Spazi pronti e connessi" : "Connected, ready-to-use spaces"}</li><li><Check />{it ? "Assistenza professionale" : "Professional support"}</li></ul><Link className="arrow-link" href={it ? "/chi-siamo.html" : "/en/about.html"}>{it ? "CONOSCI ROMA OFFICE SHARING" : "MEET ROMA OFFICE SHARING"}<ArrowRight /></Link></div></section>
      <GalleryPreview lang={lang} />
      <Cta lang={lang} />
    </> : <>
      <section className={page.kind === "customer" ? "page-hero customer-page-hero" : "page-hero"}><div className="shell"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.description}</p></div></section>
      <Breadcrumb lang={lang} title={page.title} home={home} />
      <PageBody kind={page.kind} lang={lang} pageKey={pageKey} initialService={initialService} />
    </>}
  </main>;
}

function Breadcrumb({ lang, title, home }: {lang:Lang;title:string;home:string}) { return <nav className="breadcrumb shell" aria-label="Breadcrumb"><Link href={home}>{ui[lang].home}</Link><span>/</span><span aria-current="page">{title}</span></nav>; }
function ServiceGrid({lang}:{lang:Lang}) { return <div className="service-grid">{services[lang].map(s=>{const Icon=icons[s.icon as keyof typeof icons];return <article className="service-card" key={s.title}><div className="service-icon"><Icon /></div><h3>{s.title}</h3><p>{s.text}</p><Link href={s.href}>{ui[lang].discover}<ArrowRight/><span className="sr-only">: {s.title}</span></Link></article>})}</div>; }
function Cta({lang}:{lang:Lang}) {const it=lang==="it";return <section className="cta-band"><div className="shell"><div><span className="eyebrow light">{it?"PARLIAMONE":"LET’S TALK"}</span><h2>{it?"Pronto a dare spazio alla tua attività?":"Ready to give your business room to grow?"}</h2></div><div><Link className="button accent" href={it?"/attiva.html":"/en/activate.html"}>{it?"ATTIVA SUBITO":"ACTIVATE NOW"}<ArrowRight/></Link><Link className="button secondary" href={it?"/contatti.html":"/en/contact.html"}>{it?"RICHIEDI INFORMAZIONI":"REQUEST INFORMATION"}</Link><a href={`tel:${contact.phoneHref}`}>{ui[lang].call}</a></div></div></section>}

async function PageBody({kind,lang,pageKey,initialService}:{kind:string;lang:Lang;pageKey:string;initialService:ServiceCode}) {
 const it=lang==="it"; const p=pages[pageKey]; const t=ui[lang];
 const catalog = kind === "pricing" || kind === "activation" ? await getCatalog() : null;
 if(kind==="gallery") return <Gallery lang={lang}/>;
 if(kind==="customer") return <section className="customer-shell shell"><CustomerArea lang={lang}/></section>;
 if(hasAddressDetail(pageKey)) return <><AddressServiceDetails pageKey={pageKey} lang={lang}/><Cta lang={lang}/></>;
 if(pageKey==="servizi-domiciliazione.html" || pageKey==="en/domiliation-services.html") return <>
   <section className="section shell address-overview"><div className="section-heading"><div><span className="eyebrow">{it?"DUE ESIGENZE, DUE SOLUZIONI":"TWO NEEDS, TWO SOLUTIONS"}</span><h2>{it?"Sede legale o recapito postale?":"Registered office or mailing address?"}</h2></div><p>{it?"Scegli il servizio in base all’uso dell’indirizzo. Il recapito postale non equivale alla sede legale di una società.":"Choose the service based on how you need to use the address. A mailing address is not the same as a company’s registered office."}</p></div>
   <div className="address-comparison">{services[lang].slice(1,3).map((service,index)=><article key={service.href}><span className="eyebrow">0{index+1} — {it?"LA TUA PRESENZA A ROMA":"YOUR PRESENCE IN ROME"}</span><h3>{service.title}</h3><p>{service.text}</p><p className="comparison-note">{index===0?(it?"Per indicare l’indirizzo negli atti della società, dopo verifica e conferma di attivazione.":"For use in your company’s official records, following checks and activation confirmation."):(it?"Per ricevere corrispondenza professionale senza trasferire la sede della tua attività.":"For receiving business correspondence without relocating your registered office.")}</p><Link className="button secondary" href={service.href}>{it?"Scopri cosa include":"See what’s included"}<ArrowRight/></Link></article>)}</div></section><Cta lang={lang}/></>;

 if(kind==="contact") return <section className="section shell contact-layout"><div><span className="eyebrow">{it?"SCRIVICI":"WRITE TO US"}</span><h2>{it?"Come possiamo aiutarti?":"How can we help?"}</h2><ContactForm lang={lang}/></div><aside className="contact-aside"><div className="contact-detail"><MapPin/><div><b>{it?"Indirizzo":"Address"}</b><p>{contact.address}</p></div></div><div className="contact-detail"><Phone/><div><b>{it?"Telefono":"Phone"}</b><p><a href={`tel:${contact.phoneHref}`}>{contact.phone}</a><br/>Fax {contact.fax}</p></div></div><div className="contact-detail"><Mail/><div><b>Email</b><p><a href={`mailto:${contact.email}`}>{contact.email}</a></p></div></div><div className="contact-detail"><Clock3/><div><b>{ui[lang].hours}</b><p>{ui[lang].weekdays}<br/>{ui[lang].saturday}</p></div></div><Map lang={lang}/></aside></section>;
  if(kind==="pricing") return <>
  <section className="section shell">
    <div className="section-heading"><div><span className="eyebrow">{it?"OFFERTE E TARIFFE":"OFFERS & PRICING"}</span><h2>{it?"Tutte le offerte":"All our offers"}</h2></div><p>{it?"Qui trovi le tariffe dei servizi attivabili online. Completa la richiesta nella pagina di attivazione: nessun addebito avviene prima della conferma dei dati.":"Here you find the rates of the services you can activate online. Complete the request on the activation page: no charge is made before your details are confirmed."}</p></div>
    <PricingOffer product={catalog!.legal_unit} lang={lang}/>
    <PricingOffer product={catalog!.postal} lang={lang}/>
    <OtherOffers lang={lang}/>
  </section>
  <section className="section shell process-band">
    <div className="section-heading"><div><span className="eyebrow">{it?"COME FUNZIONA":"HOW IT WORKS"}</span><h2>{it?"Attivazione in quattro passaggi":"Activation in four steps"}</h2></div><p>{it?"Dalla richiesta al pagamento, tutto online, con assistenza telefonica in ogni fase.":"From request to payment, everything is online, with telephone support at every step."}</p></div>
    <div className="timeline">
      <div><span>01</span><h3>{it?"Richiesta online":"Online request"}</h3><p>{it?"Compila i dati dell’azienda (se già esistente) e del legale rappresentante, scegli durata e data di inizio.":"Enter the company data (if it already exists) and the legal representative, then choose the duration and start date."}</p></div>
      <div><span>02</span><h3>{it?"Verifica SMS":"SMS verification"}</h3><p>{it?"Inserisci il codice ricevuto via SMS per confermare il tuo numero di telefono.":"Enter the code you receive by SMS to confirm your telephone number."}</p></div>
      <div><span>03</span><h3>{it?"Invio via email":"Email submission"}</h3><p>{it?"La richiesta viene inviata via email con il modulo in PDF e il riepilogo dei prezzi.":"Your request is emailed with the PDF form and the price summary."}</p></div>
      <div><span>04</span><h3>{it?"Pagamento":"Payment"}</h3><p>{it?"Paga con PayPal, Stripe o SumUp oppure scegli il bonifico bancario.":"Pay by PayPal, Stripe or SumUp, or choose a bank transfer."}</p></div>
    </div>
    <Link className="button primary" href={it?"/attiva.html":"/en/activate.html"}>{ui[lang].activateNow}<ArrowRight/></Link>
  </section>
  <Cta lang={lang}/>
  </>;
  if(kind==="activation") return <>
  <section className="section shell">
    <div className="section-heading"><div><span className="eyebrow">{it?"MODULO DI RICHIESTA":"REQUEST FORM"}</span><h2>{it?"Compila e attiva la domiciliazione":"Apply for your business address service"}</h2></div><p>{it?"I campi contrassegnati con * sono obbligatori. Il numero di cellulare viene verificato con un codice SMS prima dell’invio.":"Fields marked * are mandatory. Your mobile number is verified with an SMS code before submission."}</p></div>
    <ActivationFlow key={`${lang}-${initialService}`} lang={lang} catalog={catalog!} initialService={initialService}/>
  </section>
  <Cta lang={lang}/>
  </>;
 if(kind==="privacy") return <section className="section shell legal-text"><div className="notice"><FileCheck2/><p>{it?"Il testo italiano della presente informativa è la versione autorevole.":"This is a faithful English translation. In case of discrepancy, the Italian original is authoritative."}</p></div><h2>{it?"INFORMATIVA PRIVACY":"PRIVACY NOTICE"}</h2>{privacySections[lang].map(([h,b])=><section key={h}><h3>{h}</h3><p>{b}</p></section>)}<section className="customer-privacy-addendum"><h3>{it?"Area Clienti — accessi e documenti":"Customer Area — sign-in and documents"}</h3><p>{it?"L’area riservata utilizza email, password memorizzata in forma derivata non reversibile, cellulare registrato e codici SMS temporanei per verificare l’identità del cliente. Il servizio consente di scaricare esclusivamente i contratti associati al proprio account. Il caricamento di documenti di identità non è attualmente attivo.":"The private area uses your email, a non-reversible derived password hash, registered mobile and temporary SMS codes to verify your identity. You can download only contracts assigned to your own account. Identity-document uploads are not currently enabled."}</p><p>{it?"I cookie tecnici di autenticazione sono necessari per il servizio: la verifica SMS dura fino a 5 minuti e la sessione fino a 2 ore. I contratti sono conservati in uno spazio privato cifrato; gli eventi di accesso e download sono registrati per sicurezza. La pulizia programmata elimina i log oltre 90 giorni. Per assistenza, variazione del cellulare o esercizio dei diritti contatta il Titolare.":"Necessary authentication cookies support the service: the SMS challenge lasts up to 5 minutes and the session up to 2 hours. Contracts are held in encrypted private storage; login and download events are recorded for security. Scheduled cleanup removes logs older than 90 days. Contact the controller for support, registered-mobile changes or to exercise your rights."}</p></section><p><b>{ui[lang].revoke}</b></p></section>;
 if(kind==="cookies") return <section className="section shell legal-text"><h2>{it?"Cosa sono i cookie":"What cookies are"}</h2><p>{it?"I cookie sono piccoli file memorizzati dal browser. Questo sito usa cookie tecnici necessari e, con consenso, categorie analitiche e di marketing.":"Cookies are small files stored by your browser. This site uses necessary technical cookies and, with consent, analytics and marketing categories."}</p><h3>{it?"Categorie e durata":"Categories and duration"}</h3><div className="table-wrap"><table><thead><tr><th>{it?"Categoria":"Category"}</th><th>{it?"Finalità":"Purpose"}</th><th>{it?"Durata":"Duration"}</th></tr></thead><tbody><tr><td>{it?"Necessari":"Necessary"}</td><td>{it?"Preferenze consenso e sicurezza":"Consent preferences and security"}</td><td>6 {it?"mesi":"months"}</td></tr><tr><td>{it?"Analitici":"Analytics"}</td><td>{it?"Statistiche aggregate, solo previo consenso":"Aggregate metrics, only with consent"}</td><td>13 {it?"mesi":"months"}</td></tr><tr><td>Marketing</td><td>{it?"Contenuti e campagne, solo previo consenso":"Content and campaigns, only with consent"}</td><td>6 {it?"mesi":"months"}</td></tr></tbody></table></div><h3>{it?"Cookie dell’Area Clienti":"Customer Area cookies"}</h3><p>{it?"ros_customer_challenge: cookie tecnico per la verifica SMS, fino a 5 minuti. ros_customer_session: cookie tecnico di sessione, fino a 2 ore, rimosso alla disconnessione. Entrambi sono HttpOnly, SameSite=Strict e Secure in produzione; non sono cookie pubblicitari.":"ros_customer_challenge: necessary SMS-verification cookie, up to 5 minutes. ros_customer_session: necessary sign-in session cookie, up to 2 hours, removed on sign-out. Both are HttpOnly, SameSite=Strict and Secure in production; neither is an advertising cookie."}</p><h3>{it?"Gestire o revocare il consenso":"Manage or withdraw consent"}</h3><p>{it?"Usa il pulsante seguente in qualsiasi momento. Puoi anche eliminare i cookie dal browser.":"Use the button below at any time. You can also erase cookies in your browser."}</p><button className="button primary" data-cookie-settings>{ui[lang].settings}</button><p>{ui[lang].revoke}</p></section>;
 if(kind==="location") return <><section className="map-full"><Map lang={lang}/></section><section className="section shell location-grid"><div><span className="eyebrow">{it?"INDIRIZZO":"ADDRESS"}</span><h2>{contact.address}</h2><p>{it?"Siamo al primo piano di Palazzo Gentiloni, in una delle zone più centrali e ben collegate di Roma.":"We are on the first floor of Palazzo Gentiloni, in one of Rome’s most central and well-connected districts."}</p></div><div className="travel-list"><div><TrainFront/><p><b>Roma Termini</b><br/>{it?"Circa 10 minuti a piedi o poche fermate in autobus.":"Around a 10-minute walk or a short bus ride."}</p></div><div><MapPin/><p><b>Fiumicino & Ciampino</b><br/>{it?"Collegamenti ferroviari e bus diretti per Termini.":"Direct rail and coach services to Termini."}</p></div></div></section><Cta lang={lang}/></>;
 if(kind==="about") return <><section className="section shell narrative"><span className="eyebrow">{it?"DAL 2014":"SINCE 2014"}</span><h2>{it?"Siamo parte della crescita dei nostri clienti dal 2014":"We have been part of our clients’ growth since 2014"}</h2><p className="lead">{it?"Roma Office Sharing nasce dall’esperienza di Cube Engineering s.r.l. per offrire ad aziende e professionisti spazi e servizi affidabili, flessibili e curati.":"Roma Office Sharing was created from Cube Engineering s.r.l.’s experience to give businesses and professionals dependable, flexible and carefully managed spaces and services."}</p><div className="values"><div><b>01</b><h3>{it?"Missione":"Mission"}</h3><p>{it?"Liberare imprese e professionisti dagli oneri di gestione, perché possano concentrarsi sulla crescita.":"Free businesses and professionals from office overhead so they can focus on growth."}</p></div><div><b>02</b><h3>{it?"Accoglienza":"Hospitality"}</h3><p>{it?"Creare un’esperienza professionale e autenticamente romana per ogni cliente e ospite.":"Create a professional and authentically Roman experience for every client and guest."}</p></div><div><b>03</b><h3>{it?"Affidabilità":"Reliability"}</h3><p>{it?"Un rapporto trasparente, servizi puntuali e attenzione ai dettagli.":"Transparent relationships, timely services and close attention to detail."}</p></div></div></section><Cta lang={lang}/></>;
 if(kind==="testimonials") return <><section className="section shell"><div className="testimonial-grid">{[it?"Un punto di riferimento professionale e sempre disponibile.":"A professional, consistently responsive point of reference.",it?"Spazi curati e posizione davvero comoda per incontrare i clienti.":"Well-designed spaces in a genuinely convenient location for client meetings.",it?"La domiciliazione è gestita con precisione e cortesia.":"The registered office service is handled accurately and courteously."].map((q,i)=><figure key={q}><Quote/><blockquote>“{q}”</blockquote><figcaption>{it?"Testimonianza segnaposto":"Placeholder testimonial"} {i+1}<small>{it?"Sostituire con recensione verificata":"Replace with a verified review"}</small></figcaption></figure>)}</div></section><Cta lang={lang}/></>;
 return <><section className="section shell service-detail"><div><span className="eyebrow">{it?"IL SERVIZIO":"THE SERVICE"}</span><h2>{p.intro || (it?"Una soluzione professionale, semplice e flessibile":"A professional, simple and flexible solution")}</h2><p>{it?"Costruiamo il servizio intorno alle esigenze della tua attività, con assistenza dedicata e condizioni trasparenti.":"We shape the service around your organisation, with dedicated support and transparent terms."}</p>{p.bullets&&<Feature title={it?"Cosa include":"What’s included"} items={p.bullets}/>}<Link href={it?"/contatti.html":"/en/contact.html"} className="button primary">{t.activate}<ArrowRight/></Link></div><aside className="service-side"><div><b>{it?"Hai bisogno di aiuto?":"Need help?"}</b><p>{it?"Parla con il nostro team per configurare la soluzione giusta.":"Speak to our team to configure the right solution."}</p><a href={`tel:${contact.phoneHref}`} className="arrow-link"><Phone/>{t.call}</a></div></aside></section><Cta lang={lang}/></>;
}
function Feature({title,items}:{title:string;items:string[]}){return <div><h3>{title}</h3><ul className="check-list">{items.map(i=><li key={i}><Check/>{i}</li>)}</ul></div>}
function Map({lang}:{lang:Lang}){return <iframe className="map" title={lang==="it"?"Mappa di Via Venti Settembre 118, Roma":"Map of Via Venti Settembre 118, Rome"} loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=12.4935%2C41.9018%2C12.5005%2C41.9072&layer=mapnik&marker=41.9045%2C12.4970"/>}

function OtherOffers({lang}:{lang:Lang}){
  const it=lang==="it";
  const items=it?[
    {title:"Uffici arredati",text:"Uffici pronti all’uso, disponibili anche per un solo giorno.",href:"/uffici-arredati.html"},
    {title:"Sale corsi e riunioni",text:"Spazi modulari e attrezzati per meeting, colloqui e formazione.",href:"/sale-corsi.html"},
    {title:"Segreteria virtuale",text:"Supporto professionale per chiamate e comunicazioni.",href:"/segreteria-virtuale.html"}
  ]:[
    {title:"Furnished offices",text:"Ready-to-use offices, available even for a single day.",href:"/en/offices-furnished.html"},
    {title:"Training and meeting rooms",text:"Modular, fully equipped spaces for meetings and training.",href:"/en/course-rooms.html"},
    {title:"Virtual secretary",text:"Professional support for calls and communications.",href:"/en/virtual-secretary.html"}
  ];
  return <div className="offer-secondary">
    <h3>{it?"Altri servizi":"Other services"}</h3>
    <div className="service-grid secondary other-services-grid">{items.map(i=><article className="service-card" key={i.title}><h3>{i.title}</h3><p>{i.text}</p><p className="price-note">{it?"Su richiesta":"On request"}</p><Link href={i.href}>{it?"DETTAGLI":"DETAILS"}<ArrowRight/></Link></article>)}</div>
    <p className="form-note">{it?"Contattaci per un preventivo personalizzato sugli altri servizi.":"Contact us for a personalised quote for our other services."}</p>
  </div>;
}
