/* Reference Express backend for Hostinger Node plans. Install express stripe twilio pg pdfkit. */
require("dotenv").config();
const express=require("express"),crypto=require("crypto"),Stripe=require("stripe"),Twilio=require("twilio"),PDFDocument=require("pdfkit");
const {Pool}=require("pg");const db=new Pool({connectionString:process.env.DATABASE_URL});const app=express();
const stripe=process.env.STRIPE_SECRET?new Stripe(process.env.STRIPE_SECRET):null;
app.post("/api/webhook/stripe",express.raw({type:"application/json"}),async(req,res)=>{try{const event=stripe.webhooks.constructEvent(req.body,req.headers["stripe-signature"],process.env.STRIPE_WEBHOOK_SECRET);if(event.type==="checkout.session.completed")await db.query("update orders set status='paid', provider_reference=$1 where public_id=$2",[event.data.object.id,event.data.object.metadata.orderId]);res.json({received:true})}catch(e){res.status(400).send("Invalid signature")}});
app.use(express.json({limit:"2mb"}));
app.post("/api/order",async(req,res)=>{const id=crypto.randomUUID();await db.query("insert into orders(public_id,email,service,duration_months,amount_cents,status) values($1,$2,$3,$4,$5,'pending')",[id,req.body.email,req.body.service,req.body.duration,req.body.amount]);res.status(201).json({orderId:id})});
app.post("/api/create-payment-session",async(req,res)=>{if(!stripe)return res.status(503).json({error:"Configure STRIPE_SECRET"});const s=await stripe.checkout.sessions.create({mode:"payment",line_items:[{quantity:1,price_data:{currency:"eur",unit_amount:req.body.amount,product_data:{name:req.body.service}}}],metadata:{orderId:req.body.orderId},success_url:`${process.env.PUBLIC_URL}/order/${req.body.orderId}?paid=1`,cancel_url:`${process.env.PUBLIC_URL}/tariffe.html`});res.json({url:s.url})});
app.post("/api/send-otp",async(req,res)=>{const code=String(Math.floor(100000+Math.random()*900000)),hash=crypto.createHmac("sha256",process.env.OTP_SECRET).update(`${req.body.orderId}:${code}`).digest("hex");await db.query("insert into otp_verifications(order_public_id,phone,code_hash,expires_at) values($1,$2,$3,now()+interval '10 minutes')",[req.body.orderId,req.body.phone,hash]);await Twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN).messages.create({to:req.body.phone,from:process.env.TWILIO_FROM,body:`Roma Office Sharing: ${code}`});res.json({ok:true})});
app.post("/api/verify-otp",async(req,res)=>{const {rows}=await db.query("select * from otp_verifications where order_public_id=$1 and expires_at>now() and attempts<5 order by id desc limit 1",[req.body.orderId]);if(!rows[0])return res.status(400).json({error:"Expired"});const actual=crypto.createHmac("sha256",process.env.OTP_SECRET).update(`${req.body.orderId}:${req.body.code}`).digest("hex");if(!crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(rows[0].code_hash)))return res.status(400).json({error:"Invalid"});res.json({ok:true})});
app.post("/api/save-signature",(req,res)=>{const doc=new PDFDocument();res.set({"Content-Type":"application/pdf","Content-Disposition":`attachment; filename=${req.body.orderId}.pdf`});doc.pipe(res);doc.fontSize(18).text("Domiciliation request").fontSize(10).text(`Order ${req.body.orderId}\nSigned ${new Date().toISOString()}`);doc.image(Buffer.from(req.body.signature.split(",")[1],"base64"),{width:300});doc.end()});
app.post("/api/webhook/paypal",async(req,res)=>{/* Call PayPal /v1/notifications/verify-webhook-signature with all transmission headers before updating an order. */res.json({received:true})});
app.post("/api/webhook/esign",async(req,res)=>{/* Verify the provider-specific HMAC/certificate, then store only a private document key. */res.json({received:true})});
app.listen(process.env.PORT||3000);
